# Generated by Django 5.2.2 on 2025-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
